# Change these first
owner: PULSE-Delta # Your GitHub username
repo: aeonliststatus # Your GitHub repository name

# Add your sites here
sites:
  - name: Main Site
    url: https://aeon-list.com

status-website:
  theme: night
  baseUrl: /aeonliststatus
  logoUrl: 
  name: aeonliststatus
  introTitle: "**Aeonlist** Status Padge."
  introMessage: Real time status updates
  navbar:
    - title: Discord
      href: https://Discord.gg/.
